name: "10. Create Lighthouse Report  - Utility"
on:
  workflow_dispatch:
    inputs:
      delete_git_branch:
        type: boolean
        description: Delete git branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Installing Terminus
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        BASE_BRANCH=${BASE_BRANCH:0:11}
        SITE=`terminus site:info teachforamerica --field=id --format=string`
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io

        #echo Running terminus site:info teachforamerica --field=id --format=string
        #terminus site:info teachforamerica --field=id --format=string
        echo Ran teachforamerica.$BASE_BRANCH
        echo Got this ID $SITE
        echo want report for $URL

        echo Running ls -l
        ls -l

        rsync -rLvz --size-only --checksum --ipv4 --progress -e 'ssh -p 2222' --temp-dir=~/tmp/ unlighthouse files/sunlighthouse
        echo bye
        
        
