name: Create Lighthouse Report
on:
  workflow_dispatch:
    inputs:
      delete_git_branch:
        type: boolean
        description: Delete git branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Installing Terminus.
      uses: kopepasah/setup-pantheon-terminus@master
      with:
        pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: Installing dependencies.
      run: npm install -g @unlighthouse/cli puppeteer netlify-cli

    - name: Waking Up Multidev.
      run: |
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io
        BASE_BRANCH=${GITHUB_REF##*/}
        BASE_BRANCH=${BASE_BRANCH:0:11}
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io

        #Wake Up call.
        #echo Waking Up Multidev.
        terminus env:wake teachforamerica.$BASE_BRANCH
      
    - name: Run UNLighthouse Report.
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        BASE_BRANCH=${BASE_BRANCH:0:11}
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io
        URL=https://www.teachforamerica.org

        echo Running the Lighthouse Report
        unlighthouse-ci --site $URL --build-static --reporter csvExpanded
        echo Finished the Lighthouse Report

        echo Renaming UNLighthouse report.
        #mv ./unlighthouse unlighthouse

        echo Running ls -a -l
        ls -a -l

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
        pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        BASE_BRANCH=${BASE_BRANCH:0:11}
        SITE=`terminus site:info teachforamerica --field=id --format=string`
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io
        USER=$BASE_BRANCH.$SITE
        SOURCE_PATH=.unlighthouse/
        DESTINATION_PATH=$USER@appserver.$BASE_BRANCH.$SITE.drush.in:/files/unlighthouse
        
        #echo Running terminus site:info teachforamerica --field=id --format=string
        #terminus site:info teachforamerica --field=id --format=string
        echo Ran teachforamerica.$BASE_BRANCH
        echo Got this ID $SITE
        echo want report for $URL
        echo USER = $USER
        echo DESTINATION_PATH = $DESTINATION_PATH

        echo Running ls -a -l
        ls -a -l

        echo Running rsync to copy files to multidev.
        rsync -rLvz --size-only --checksum --ipv4 --progress -e 'ssh -p 2222' --temp-dir=~/tmp/ $SOURCE_PATH $DESTINATION_PATH

    - name: Show Output Links
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        BASE_BRANCH=${BASE_BRANCH:0:11}
        URL=https://$BASE_BRANCH-teachforamerica.pantheonsite.io
        REPORT_LINK=$URL
        REPORT_LINK+='/sites/default/files/unlighthouse/'
        UNLIGHTHOUSE_LINK=$URL
        UNLIGHTHOUSE_LINK+='/sites/default/files/unlighthouse/ci-result.csv'
        echo Report: $REPORT_LINK
        echo Lighthouse: $UNLIGHTHOUSE_LINK

        echo bye
