name: Audit cur1 main
on: 
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - name: Step One.
      run: |
        URL=https://teachforamerica.org
        echo Stepp 1 URL = $URL


   
