name: Audit cur1 main
on:
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - name: Step One.
      run: |
        URL=https://teachforamerica.org
        echo Stepppp 1 URL = $URL

    - name: Output Links
      run: |
        REPORT_LINK=$URL
        REPORT_LINK+='/sites/default/files/unlighthouse/index.html'
        UNLIGHTHOUSE_LINK=$URL
        UNLIGHTHOUSE_LINK+='/sites/default/files/unlighthouse/ci-result.csv'
        echo Report: $REPORT_LINK
        echo Lighthouse: $UNLIGHTHOUSE_LINK
  



   
