name: Audit cur1 main
on:
  workflow_dispatch:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
    - name: Step One.
      run: |
        URL=https://teachforamerica.org
        echo Stepppp 1 URL = $URL

    - name: Step Two.
      run: |
        URL=https://teachforamerica.org
        REPORT_LINK=$URL
        REPORT_LINK+='/sites/default/files/unlighthouse/index.html'
        UNLIGHTHOUSE_LINK=$URL
        UNLIGHTHOUSE_LINK+='/sites/default/files/unlighthouse/ci-result.csv'
        echo $REPORT_LINK
        echo $UNLIGHTHOUSE_LINK
        echo Step 2 URL = $URL



   
