name: UN Lighthouse

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
#        run: unlighthouse-ci --site <your-site> --budget 75 --build-static
        run: unlighthouse-ci --site https://www.teachforamerica.org --build-static --reporter csvExpanded

      - name: Display
        run: cp ./unlighthouse/ci-result.csv . && ls && git config --global user.email "seth@sethsnyder.com" && git config --global user.name "Seth Snyder" && git add -A && git commit -m "after run"
