name: Upload to GDrive

#
# This workflow will run a command on a cloud hosted Ubuntu Actions runner and open an issue
# with the output of the shell command
#

on:
  workflow_dispatch:
    inputs:
      command:
        description: The command to run
        default: curl https://api.github.com/octocat

jobs:
  run-command:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Upload a file to Google Drive
      uses: nextDriveIoE/google-drive-upload-action@v2
      with:
        target: report.csv
        credentials: "ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGZhLWxpZ2h0aG91c2UtcmVwb3J0cyIsCiAgInByaXZhdGVfa2V5X2lkIjogIjNhNWVlYjg2MzY0MzJlNDA1ODFjMzQxYmU4MzJiZmE5MzllYmIwZGYiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV1d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktVd2dnU2hBZ0VBQW9JQkFRQ2hGbGF3YVc2WlVrck9cbjJkL25kVzh2ZE5rSURZWlVqM2hxU3hVdEFiL25UdTRaRjZPZ1VNamp5WEl2M0wwZTNBOUI4NTFzQkdvZzVuM0xcbmw2R2ZkWjEzellKS0JiOUR3QXE1NlVyL0c5d2luVVYrS09pZklkSDV5S0s4K2JGWlFUY2hyNU5HcCtYSjhaamVcbnJLR0d6NkthVldOQ0RMdDdHbFZuL0wwaU9RZU4zNjJxV0Vpc0hzZGZPeEZBZTkrWlQ2OWhjbDhBV0lzTkU3OUNcbnpocEN0OU1OcjhMMGNCWDRjNnFyQ3c2NWdhZkQ4YXo1ZzhrRTZQQ2xUWm5MRGg3UENNbEpUSkN4ejl2WjZDNkxcbnphUHlJK1JqOWVOMWRaRlNLUTREeTNPcXl6ZWVFbi8xaVREWTN1ZDdZeEpnVU9SVnUvb2ZiUncrN2hUTVFqR1ZcbmVvOFhsL2w5QWdNQkFBRUNnZjlZVG5vekM0ZlNqZFVaaDMzVE1Nb3EvUk1KNnB6Z043MlhJN1NhekRnSDMwNXpcbkR5Ly9FZndUQmdUdCswUC8wakpPVEE2bFFtc29TNXJFYVU1Y0UxWlE2alZLQ0NxZHB1NjhpdzJFM1l6bHNrU2FcbldiQUZKRWhvVHpVK0ZVUVdwWDQ0ZjdsMVB3N1RUdmxPNUlPd3BLVFZxQk9hbytzTlF2bzhackFweElZcmpYcU9cbnNpMXRmd1JKY0RLL0htdmQ5YmlxZ1RHTG52dkVvWEE5UHB2dkFyWnk1d0FjQW5FM2VoQWsxSDVjc2xCV01NNmhcblN4bE1CWVlLUDcvMVVaTGtiemNyelNuUlhnb3NDdUc0eU5ESGtPZHRGRkpkK3NyZDNHaUJyRmdoK1FnVm5TYlVcbmdpcnFaYkFuUUhHeksrQW9rN0dFSzJrYnM1cUQyOGRvTWM5NkUrRUNnWUVBekZ0RGhaK2NqZjB6SzRjYzVGWitcbm9HZjlsTHlTTzdicWpBRlNJQnlqdVNjWmpXVW0wVk8wUjJPd1F5R0pHdlhJK3BKTGRmY2JybjYwMys3Si93R0ZcbnlkejVzSzEwYU5ZSHNINzlxc0d1KzFqM2lrVGhTZ0tyNnhwVlRNa3ZqWk1LUDlwSms2NXJDMFYvdVl0aGFubTBcbk5NTGVDZ2V2cm5VZnJGQm52ZnZrbDFNQ2dZRUF5Y3ZMVWlpUEpCTUtXZ0pZcFcySHF4Uy9FRXVRYWUxZmhHZkFcblhhaFJjQ2lHbEh5dnRvakNqb04vMk5EcU5UZFpVTkE0STRuWFV5cTR0UmVJejhZRHVvUUJ3VHkxL1VFaE9xVnBcbjVFZkF2ZDF6Ymp2MnRWR0RLSnhUMDdINUE4azhpT0dPck05RUF0ZktneDkzK3RXanZsUG5pWFE1d3lHelhEQzNcblRoNy9JZThDZ1lCMmtCQ1p5eVBpZ1YrWnhuY3R4ejBLUmFzckMwandXa3kwVStQWSs2VEZ2SGludjJNSkdiNURcbm1RUGZ2dW96K1J2VXZPSUpIQWcwY2hEd3h6THN2MjVtMHMwUEEyUEJtME8wMDhqS3REcVlXMktyRnhGNmhoaEdcbmUrMjNjaFlqMW9hZ3l6M2E3OXZ0R3pKaWJRcGs0eDE1YXdHMTRnVzhldm1ZV01JSHlNZzBQd0tCZ0MzZDFHam9cbkx5RFQ4eFppVWlQSHNYNkJTS3c3Z0tlUy9KTHJ3aDJIbEhzWnV2MGxHZ3N6S29XWi9nVVo5eUlCWXB1cnVCYmJcbnpjVnBnSElvMXovaWtoWml5c05ST1V4RzhYYVRBbTZRb0k2SE55Vm5HN3c2dXNVUVF6MXF4bDdGN3F4dUdDL1BcbkxIWTQ5aDYzbUYyN0VXekJSVzlJcTVoZW9KWGp2TVpVNVVpaEFvR0JBSXlIa3lhQ3lqUEJCa2cvS3BNTnVJQnRcbi90U1F1MVlpT1Jubnc2VnNUTSt0ZE93RTQzSERtQnFRUnhVUStSMytFcmQwRjl1Ly9acEt5ZGcvRkhYZmhpTUtcbnVGQjg2MEhQN3I0ZGtlcDdTYVdXVXFUdm0raTNFSFN5ZlczM3pVVFBDMUJ0TDVuWnFSdWpFREordE92OFFHZVVcbjBQWHdKbzg3WTVnS2IwT1gvQjV5XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAidGZhLWxpZ2h0aG91c2UtcmVwb3J0cy1zYWlkQHRmYS1saWdodGhvdXNlLXJlcG9ydHMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAwNDEwMTk3NTY2NzQ3Njg1MTAyIiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90ZmEtbGlnaHRob3VzZS1yZXBvcnRzLXNhaWQlNDB0ZmEtbGlnaHRob3VzZS1yZXBvcnRzLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg=="
        parent_folder_id: 1hSA0uCmunRMFXwZsZWaj9shPdV53OOwb
      #
      # actions/github-script is a very powerful action which allows you to
      # easily run a script in your workflow that uses the GitHub API and the
      # workflow run context.
      #
      # To learn more, visit https://github.com/actions/github-script.
      #
      - name: Run command
